version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - kafka

  broker:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
      - 9096:9096
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT'
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092,SASL_PLAINTEXT://broker:9096'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server.conf"
      KAFKA_LISTENERS: 'PLAINTEXT://broker:9092,SASL_PLAINTEXT://broker:9096'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-512'
      KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
      KAFKA_SUPER_USERS: 'User:admin,User:redpanda'
    volumes:
      - ./kafka/config/:/etc/kafka/jaas/
    depends_on:
      - zookeeper
    networks:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.2
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9096
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="redpanda" password="redpandasecret123";'
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - kafka
    ports:
      - 8080:8080

networks:
  kafka:
    driver: bridge